config/routes.rb
Rails.application.routes.draw do
  get 'file_data/add_file'
  post 'file_data/download'
  get 'file_data/download_history'
  
  resources :customers
  devise_for :users
  resources :users
  resources :groups do
    member do
      get :member_ship
      get :members
      get :add_members
    end
    collection do
      get :customers
    end
    resources :categories
  end
  resources :categories, only: :index do
    resources :posts
    resources :documents
  end
  resources :posts, only: :index do
    resources :comments
  end
  resources :documents, only: :index
  root 'dashboard#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :customer
  has_many :categories
  has_many :posts, through: :categories
  has_many :documents, through: :categories
  has_attached_file :image
  validates :name, uniqueness: true
  validates_attachment_content_type :image\
  , content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  def self.groups
    where(is_deleted: false).order(created_at: :desc)
  end

  def self.customer_groups(customer_id)
    where(customer_id: customer_id, is_deleted: false).order(created_at: :desc)
  end

  def group_users
    users.where(is_deleted: false).order(created_at: :asc)
  end

  def live_categories
    categories.where(is_deleted: false).order(created_at: :desc)
  end

  def group_admin
    role = Role.find_by(name: 'GroupAdmin')
    users.find_by(role_id: role.id)
  end

  def has_pic
    return 'photo1.png' if image.blank?
    image
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy,
                                   :member_ship, :members, :add_members]
  before_action :set_users, only: [:new, :create]

  def index
    if current_user.super_admin?
      @groups = Group.groups
    elsif current_user.admin?
      @groups = Group.customer_groups(current_user.customer_id)
    else
      @groups = current_user.has_groups
    end
    authorize! :read, Group
  end

  def show
    @category = @group.categories.build
    authorize! :show_read, @group
  end

  def new
    @group = Group.new
    authorize! :create, @group
  end

  def edit
    @users = User.customer_users(@group.customer_id)
    authorize! :update, @group
  end

  def create
    @group = Group.new(group_params)
    @group.customer_id = current_user.customer_id unless current_user.super_admin?
    if @group.save
      assign_group_admin(params[:user])
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def assign_group_admin(user)
    user = User.find_by(id: user[:id])
    role = Role.find_by(name: 'GroupAdmin')
    user.update(role_id: role.id)
    GroupsUser.create(user_id: user.id, group_id: @group.id)
  end

  def update
    @users = User.customer_users(@group.customer_id)
    if @group.update(group_params)
      update_group_admin(params[:user])
      redirect_to groups_path, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def update_group_admin(user)
    user = User.find_by(id: user[:id])
    return if @group.group_admin.eql? user
    remove_old_group_admin
    assign_group_admin(user)
  end

  def remove_old_group_admin
    user = @group.group_admin
    gu = GroupsUser.find_by(user_id: user.id, group_id: @group.id)
    gu.destroy if gu
    return unless user.groups.blank?
    role = Role.find_by(name: 'Member')
    user.update(role_id: role.id)
  end

  def destroy
    authorize! :delete, @group
    @group.update(is_deleted: true)
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  def member_ship
    user = User.find_by(id: params[:user_id])
    if params[:event].eql? 'add'
      GroupsUser.create(user_id: user.id, group_id: @group.id)
    else
      member = GroupsUser.find_by(user_id: user.id, group_id: @group.id)
      member.destroy if member
    end
    redirect_to groups_path, notice: "User #{params[:event]} in group successfully"
  end

  def members
    @users = @group.group_users
    authorize! :update, @group
  end

  def add_members
    @users = User.add_users(@group.customer_id)
    authorize! :update, @group
  end

  def customers
    @group = Group.new
    @customer = Customer.find(params[:customer_id])
    @users = User.customer_users(@customer.id)
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def set_users
    @customers = Customer.customers
    if current_user.super_admin?
      @users = User.users_for_group
    else
      @users = User.customer_users(current_user.customer_id)
    end
  end

  def group_params
    params.require(:group).permit(:name, :status, :customer_id, :image)
  end
end

app/views/groups/_form.html.erb
<%= bootstrap_form_for(@group, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-7", html: {id: 'group_form'}) do |f| %>
  <div class="row">
  	<div class="col-md-8">
	  <%= f.text_field :name, placeholder: 'Name' %>
	  <%= f.text_field :status, placeholder: 'Status' %>
	  <%= f.select :customer_id, @customers.collect { |c| [c.name, c.id] },{prompt: true}, {onchange: "send_customer()"} if current_user.super_admin? && @group.new_record? %>
  	  <div class="users"><%= render 'users' %></div>
	</div>
	<div class="col-md-4">
	  <%= image_tag @group.image? ? @group.image : '', class: 'image-pic' %>
	  <%= f.file_field :image, onchange: "readFile(this);" %>
	</div>
  </div>
  <div class="col-sm-2 col-sm-offset-2">
    <%= f.submit "Save", class: "btn btn-primary btn-block btn-flat" %>
  </div>
<% end %>

app/views/groups/_users.html.erb
<div class="form-group">
	<div class="col-sm-3">
		<%= label_tag :group_admin, 'Group Admin',class: 'pull-right'%>
	</div>
	<div class="col-sm-7">
		<%= select :user, :id, @users.collect { |u| [u.full_name, u.id] },{prompt: true, selected: @group.group_admin ? @group.group_admin.id : ''},{class: 'form-control'} %>
	</div>
</div>

app/views/groups/add_members.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Add Members</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table class="table table-striped table-hover datatable">
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= user.full_name %></td>
                <td><%= user.email %></td>
                <td><%= user.role_name %></td>
                <td><% if user.group_member(@group) %>Member<%else%><%= link_to 'Add', member_ship_group_path(@group, event: 'add', user_id: user.id), data: { confirm: 'Are you sure?' } %><%end%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>

app/views/groups/customers.js.erb
$('.users').html("<%= j render 'users' %>");

app/views/groups/edit.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="box box-success">
			<div class="box-header">
				<h3 class="box-title">Edit Group</h3>
			</div>
			<div class="box-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/groups/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Groups List</h3>
        <div class="pull-right"><%= link_to 'New Group', new_group_path, class: 'btn btn-primary btn-xs btn-flat' if can? :create, Group %>
        </div>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table class="table datatable group">
          <thead>
            <tr>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @groups.each_slice(3) do |groups| %>
            <tr>
              <% groups.each do |group|%>
              <td>
                <div class="small-box bg-aqua">
                  <div class="inner">
                    <h4><%= group.name %></h4>
                    <div class="status">
                      <%= group.status %>
                    </div>
                    <div class="group-action">
                      <%if can? :update, group %><%= link_to edit_group_path(group) do%><i class="fa fa-edit"></i><%end%><%end%>&nbsp;&nbsp;
                      <%if can? :update, group%><%= link_to group, method: :delete, data: { confirm: 'Are you sure?' } do%><i class="fa fa-trash"></i><%end%><%end%>&nbsp;&nbsp;
                      <%if can? :update, group%><%= link_to add_members_group_path(group) do %><i class="fa fa-user-plus"></i><%end%><%end%>&nbsp;&nbsp;
                      <%if can? :update, group%><%= link_to members_group_path(group) do%><i class="fa fa-users"></i><%end%><%end%>&nbsp;&nbsp;
                    </div>
                  </div>
                  <div class="icon">
                    <%= image_tag group.has_pic, alt: "Group Image", class: 'group-image'%>
                  </div>
                  <% if can? :show_read, group %>
                  <%= link_to group_path(group), class: "small-box-footer" do %>More info <i class="fa fa-arrow-circle-right"></i><%end%>
                  <%end%>
                </div>
              </td>
              <%end%>
              <%= table_td(groups)%>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>

app/views/groups/members.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Members</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table class="table table-striped table-hover datatable">
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= user.full_name %></td>
                <td><%= user.email %></td>
                <td><%= user.role_name %></td>
                <td><%= link_to 'Remove', member_ship_group_path(@group, event: 'remove', user_id: user.id), data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>

app/views/groups/new.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">New Group</h3>
			</div>
			<div class="box-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/groups/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Categories List</h3>
        <div class="pull-right"><%= link_to 'New Category',  new_group_category_path(@group), class: 'btn btn-primary btn-xs btn-flat' if can? :create, @category %>
        </div>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table class="table datatable group">
          <thead>
            <tr>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @group.live_categories.each_slice(3) do |categories| %>
            <tr>
              <% categories.each do |category| %>
              <td>
                <div class="info-box">
                  <span class="info-box-icon bg-aqua"><i class="fa fa-navicon"></i></span>
                  <div class="info-box-content">
                    <span class="info-box-text"><%= link_to category.name, group_category_path(@group, category) %></span>
                    <span class="info-box-number"><small><%= category.description %></small></span>
                    <div class="category-action">
                      <%if can? :update, category %><%= link_to edit_group_category_path(@group, category) do %><i class="fa fa-edit"></i><%end%><%end%>&nbsp;&nbsp;
                      <%if can? :delete, category%><%= link_to [@group, category], method: :delete, data: { confirm: 'Are you sure?' } do%><i class="fa fa-trash"></i><%end%><%end%>
                    </div>
                  </div>
                </div>
              </td>
              <%end%>
              <%= table_td(categories)%>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>