config/routes.rb
Rails.application.routes.draw do
  get 'file_data/add_file'
  post 'file_data/download'
  get 'file_data/download_history'
  
  resources :customers
  devise_for :users
  resources :users
  resources :groups do
    member do
      get :member_ship
      get :members
      get :add_members
    end
    collection do
      get :customers
    end
    resources :categories
  end
  resources :categories, only: :index do
    resources :posts
    resources :documents
  end
  resources :posts, only: :index do
    resources :comments
  end
  resources :documents, only: :index
  root 'dashboard#index'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :users
  has_many :groups
  has_many :posts, through: :groups
  has_many :documents, through: :groups
  has_attached_file :logo
  validates_attachment_content_type :logo\
  , content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  def self.customers
    where(is_deleted: false, is_disabled: false).order(created_at: :desc)
  end

  def live_users
    users.where(is_deleted: false).order(created_at: :desc)
  end

  def live_posts
    posts.where(is_deleted: false).order(created_at: :desc)
  end

  def live_documents
    documents.where(is_deleted: false).order(created_at: :desc)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.customers
    authorize! :read, @customers
  end

  def show
    authorize! :read, @customer
  end

  def new
    @customer = Customer.new
    authorize! :create, @customer
  end

  def edit
    role = Role.find_by(name: 'Admin')
    @user = @customer.users.find_by(role_id: role.id)
    authorize! :update, @customer
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      create_customer_admin(user_params)
      redirect_to customers_path, notice: 'Customer was successfully created.'
    else
      render :new
    end
  end

  def create_customer_admin(user_params)
    role = Role.find_by(name: 'Admin')
    user = User.new(user_params)
    user.customer_id = @customer.id
    user.role_id = role.id
    user.save
  end

  def update
    if @customer.update(customer_params)
      update_customer_admin(user_params)
      redirect_to customers_path, notice: 'Customer was successfully updated.'
    else
      render :edit
    end
  end

  def update_customer_admin(user_params)
    role = Role.find_by(name: 'Admin')
    user = @customer.users.find_by(role_id: role.id)
    return create_customer_admin(user_params) unless user
    user.update(user_params)
  end

  def destroy
    authorize! :delete, @customer
    @customer.update(is_deleted: true)
    redirect_to customers_url, notice: 'Customer was successfully destroyed.'
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :street, :city, :state, :country, :pincode, :email, :contact_no, :logo, :is_deleted, :is_disabled)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :contact_no, :password)
  end
end

app/views/customers/_form.html.erb
<%= bootstrap_form_for(@customer, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-7", html: {id: 'customer_form'}) do |f| %>
  <div class="row">
    <div class="col-md-8">
      <%= f.text_field :name, placeholder: 'Name' %>
      <%= f.text_field :street, placeholder: 'Street' %>
      <%= f.text_field :city, placeholder: 'City' %>
      <%= f.text_field :state, placeholder: 'State' %>
      <%= f.text_field :country, placeholder: 'Country' %>
      <%= f.text_field :pincode, placeholder: 'Pincode' %>
      <%= f.email_field :email, placeholder: 'Email' %>
      <%= f.text_field :contact_no, placeholder: 'Contact No' %>
    </div>
    <div class="col-md-4">
      <%= image_tag @customer.logo? ? @customer.logo : '', class: 'image-pic' %>
      <%= f.file_field :logo, onchange: "readFile(this);"%>
    </div>
  </div>
  <h4>Customer Primary Admin Details</h4>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :user_first_name, class: 'pull-right'%>
    </div>
    <div class="col-sm-4">
      <%= text_field :user, :first_name, value: @user ? @user.first_name : "", placeholder: 'First Name', class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :user_last_name, class: 'pull-right'%>
    </div>
    <div class="col-sm-4">
     <%= text_field :user, :last_name, value: @user ? @user.last_name : "", placeholder: 'Last Name', class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :user_contact_no, class: 'pull-right'%>
    </div>
    <div class="col-sm-4">
     <%= text_field :user, :contact_no, value: @user ? @user.contact_no : "", placeholder: 'Contact No', class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :user_email, class: 'pull-right'%>
    </div>
    <div class="col-sm-4">
     <%= email_field :user, :email, value: @user ? @user.email : "", placeholder: 'Email', class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :user_password, class: 'pull-right'%>
    </div>
    <div class="col-sm-4">
     <%= password_field :user, :password, placeholder: 'Password', class: 'form-control' %>
    </div>
  </div>
  <div class="col-sm-2 col-sm-offset-2">
    <%= f.submit "Save", class: "btn btn-primary btn-block btn-flat" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="box box-success">
			<div class="box-header">
				<h3 class="box-title">Edit Customer</h3>
			</div>
			<div class="box-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Customers List</h3>
        <div class="pull-right"><%= link_to 'New Customer', new_customer_path, class: 'btn btn-primary btn-xs btn-flat' %></div>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table class="table datatable">
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Country</th>
              <th>Email</th>
              <th>Contact no</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.name, customer_path(customer) %></td>
              <td><%= customer.country %></td>
              <td><%= customer.email %></td>
              <td><%= customer.contact_no %></td>
              <td><%= link_to edit_customer_path(customer) do %><i class='fa fa-edit'></i><%end%></td>
              <td><%= link_to customer, method: :delete, data: { confirm: 'Are you sure?' } do %><i class='fa fa-trash'></i><%end%></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>

app/views/customers/new.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">New Customer</h3>
			</div>
			<div class="box-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/customers/show.html.erb
<%= render '/users/list', users: @customer.live_users, customer: @customer %>