config/routes.rb
Rails.application.routes.draw do
  get 'file_data/add_file'
  post 'file_data/download'
  get 'file_data/download_history'
  
  resources :customers
  devise_for :users
  resources :users
  resources :groups do
    member do
      get :member_ship
      get :members
      get :add_members
    end
    collection do
      get :customers
    end
    resources :categories
  end
  resources :categories, only: :index do
    resources :posts
    resources :documents
  end
  resources :posts, only: :index do
    resources :comments
  end
  resources :documents, only: :index
  root 'dashboard#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  has_many :comments
  has_many :file_data

  def live_comments
    comments.where(is_deleted: false).order(created_at: :desc)
  end

  def self.posts
    where(is_deleted: false).order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.super_admin?
      @posts = Post.posts
    elsif current_user.admin?
      @posts = current_user.customer_posts
    else
      @posts = current_user.live_posts
    end
  end

  def show
    @comment = @post.comments.build
    readed_notifications
    authorize! :read, @post
  end

  def new
    @category = Category.find(params[:category_id])
    @post = @category.posts.build
    authorize! :create, @post
  end

  def edit
    authorize! :update, @post
  end

  def create
    @category = Category.find(params[:category_id])
    @post = @category.posts.new(post_params)
    if @post.save
      attach_files(params[:files])
      send_notifications
      redirect_to group_category_path(@category.group, @category)\
      , notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      attach_files(params[:files])
      redirect_to group_category_path(@category.group, @category)\
      , notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize! :delete, @post
    @post.update(is_deleted: true)
    redirect_to group_category_path(@category.group, @category)\
    , notice: 'Post was successfully destroyed.'
  end

  def attach_files(files)
    return if files.blank?
    files.each { |file| @post.file_data.create(file: file) }
  end

  def send_notifications
    group = @category.group
    group.group_users.each do |u|
      next if current_user.eql? u
      Notification.create(user_id: u.id, post_id: @post.id)
    end
  end

  def readed_notifications
    nf = current_user.unread_ntfs.find_by(post_id: @post.id)
    nf.update(is_readed: true) if nf
    @post.live_comments.each do |cm|
      nf2 = current_user.unread_ntfs.find_by(comment_id: cm.id)
      nf2.update(is_readed: true) if nf2
    end
  end

  private

  def set_post
    @category = Category.find(params[:category_id])
    @post = @category.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end
end

app/views/posts/_form.html.erb
<%= bootstrap_form_for([@category, @post], layout: :horizontal, label_col: "col-sm-1", control_col: "col-sm-11", html:{id: 'post_form', :class => 'form-horizontal', multipart: true }) do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :content %>
  <br/>
  <div class="form-group">
    <div class="col-sm-1">
      <%= f.label :files, class: 'pull-right'%>
    </div>
    <div class="col-sm-4">
      <%= link_to 'Add file', file_data_add_file_path, remote: true, class: 'btn btn-info btn-flat btn-xs' %>
    </div>
  </div>
  <div class="row">
	  <div class="col-sm-4 col-sm-offset-1">
	  	<%= render '/file_data/files', object: @post %><br/>
	  	<div class="files"></div>
	  </div>
  </div>
  <div class="col-sm-2 col-sm-offset-5">
    <%= f.submit "Save", class: "btn btn-primary btn-block btn-flat" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<h4><%= link_to post.title, category_post_path(category, post) %></h4>
<div class="pull-right">
	<%if can? :update, post%><%= link_to edit_category_post_path(category,post) do%><i class="fa fa-edit"></i><%end%><%end%>&nbsp;&nbsp;&nbsp;&nbsp;
	<%if can? :delete, post%><%= link_to [category, post], method: :delete, data: { confirm: 'Are you sure?' } do%><i class="fa fa-trash"></i><%end%><%end%>
</div>
<p><i class="fa fa-clock-o"></i> Posted on <%= post.created_at.to_datetime %></p>
<p><%= post.content.html_safe %></p>
<%= link_to category_post_path(category, post), class: 'btn btn-primary btn-xs' do %>Read More <i class="fa fa-angle-right"></i><%end%>
<hr>

app/views/posts/edit.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="box box-success">
			<div class="box-header">
				<h3 class="box-title">Edit Post</h3>
			</div>
			<div class="box-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Posts List</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table class="table datatable">
          <thead>
            <tr>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td>
                  <%= render '/posts/post', category: post.category, post: post %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="box box-primary">
			<div class="box-header">
				<h3 class="box-title">New Post</h3>
			</div>
			<div class="box-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box box-info">
      <div class="box-header">
        <h3 class="box-title"><%= @post.title %><hr></h3>
      </div>
      <div class="box-body">
        <p><i class="fa fa-clock-o"></i> Posted on <%= @post.created_at.to_datetime %></p>
        <hr>
        <%= @post.content.html_safe %>
        <hr>
        <%= render '/file_data/files', object: @post %>
        <hr>
        <div class="well">
          <h4>Leave a Comment:</h4>
          <%= render '/comments/form' %>
        </div>
        <table class="table">
          <% @post.live_comments.each do |comment|%>
          <tr>
            <td>
              <div class="media">
                <a class="pull-left" href="#">
                  <i class="fa fa-comments"></i>
                </a>
                <div class="media-body">
                  <h4 class="media-heading"><%= comment.user_name %>
                    <small><%= comment.created_at.to_datetime %></small>
                  </h4>
                  <%= comment.content %>
                </div>
              </div>
            </td>
            <td><%if can? :delete, comment %><%= link_to [@post, comment], method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-trash"></i><%end%><%end%></td>
          </tr>
          <%end%>
        </table>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>