config/routes.rb
Rails.application.routes.draw do
  get 'file_data/add_file'
  post 'file_data/download'
  get 'file_data/download_history'
  
  resources :customers
  devise_for :users
  resources :users
  resources :groups do
    member do
      get :member_ship
      get :members
      get :add_members
    end
    collection do
      get :customers
    end
    resources :categories
  end
  resources :categories, only: :index do
    resources :posts
    resources :documents
  end
  resources :posts, only: :index do
    resources :comments
  end
  resources :documents, only: :index
  root 'dashboard#index'
end

app/views/layouts/_content_header.html.erb
<section class="content-header">
	<h1>
		<%= current_controller %>
		<small><%= current_action %></small>
	</h1>
	<ol class="breadcrumb">
		<li><%= link_to root_path do %><i class="fa fa-dashboard"></i> Dashboard<%end%></li>
		<li class="active"><%= current_controller %></li>
	</ol>
</section>

app/views/layouts/_flash_message.html.erb
<% if notice %>
	<%= content_tag :javascript do%>
		<script type="text/javascript">
			flash_msg("<%= notice %>");
		</script>
	<% end %>
<% end %>
<% if alert %>
	<%= content_tag :javascript do%>
		<script type="text/javascript">
			flash_msg("<%= alert %>",'error');
		</script>
	<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
	<div class="pull-right hidden-xs">
		<b>Version</b> 2.0
	</div>
	<strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
	<%= link_to root_path, class: "logo" do %>
	<!-- mini logo for sidebar mini 50x50 pixels -->
	<span class="logo-mini"><b>S</b>F</span>
	<!-- logo for regular state and mobile devices -->
	<span class="logo-lg"><b>Student</b>Forum</span>
	<%end%>

	<!-- Header Navbar: style can be found in header.less -->
	<nav class="navbar navbar-static-top" role="navigation">
		<!-- Sidebar toggle button-->
		<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>
		<!-- Navbar Right Menu -->
		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">
				<!-- Notifications: style can be found in dropdown.less -->
				<li class="dropdown notifications-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-bell-o"></i>
						<span class="label label-warning"><%= current_user.ntfs_count %></span>
					</a>
					<ul class="dropdown-menu">
						<li class="header">You have <%= current_user.ntfs_count %> notifications</li>
						<li>
							<!-- inner menu: contains the actual data -->
							<ul class="menu">
								<% current_user.unread_ntfs.each do |nf|
								%>
								<%= render 'layouts/notifications', nf: nf %>
								<%end%>
							</ul>
						</li>
						<li class="footer"><a href="#">Notifications</a></li>
					</ul>
				</li>
				<!-- User Account: style can be found in dropdown.less -->
				<li class="dropdown user user-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					    <%= image_tag current_user.has_pic, class: "user-image", alt: "User Image"%>
						<span class="hidden-xs"><%= current_user.email %></span>
					</a>
					<ul class="dropdown-menu">
						<!-- User image -->
						<li class="user-header">
						    <%= image_tag current_user.has_pic, class: "img-circle", alt: "User Image"%>
							<p>
								<%= current_user.full_name %>
								<small><%= current_user.role_name%> <%= current_user.join_date %></small>
							</p>
						</li>
						<!-- Menu Footer-->
						<li class="user-footer">
							<div class="pull-left">
								<%= link_to 'Profile', edit_user_path(current_user), class: "btn btn-default btn-flat" %>
							</div>
							<div class="pull-right">
								<%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-default btn-flat" %>
							</div>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</header>

app/views/layouts/_index.html.erb
<div class="wrapper">
	<%= render 'layouts/header' %>
	<!-- Left side column. contains the logo and sidebar -->
	<%= render 'layouts/slider'%>
	<!-- Content Wrapper. Contains page content -->
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<%= render 'layouts/content_header'%>
		<!-- Main content -->
		<section class="content">
			<%= yield %>
		</section><!-- /.content -->
	</div><!-- /.content-wrapper -->
	<%= render 'layouts/footer' %>
</div><!-- ./wrapper -->

app/views/layouts/_notifications.html.erb
<% if nf.post_ntfs? %>
	<% post = nf.post %>
	<li>
		<%= link_to category_post_path(post.category, post) do %>
			<i class="fa fa-newspaper-o"></i> New post <%= post.title %> posted on group <%= post.category.group.name %>
		<%end%>
	</li>
<%end%>
<% if nf.comment_ntfs? %>
	<% post = nf.comment.post %>
	<li>
		<%= link_to category_post_path(post.category, post) do %>
			<i class="fa fa-comment"></i> New comment added on post <%= post.title %>
		<%end%>
	</li>
<%end%>
<% if nf.document_ntfs? %>
	<% document = nf.document %>
	<li>
		<%= link_to documents_path do %>
			<i class="fa fa-newspaper-o"></i> New document <%= document.title %> uploaded on group <%= document.category.group.name %>
		<%end%>
	</li>
<%end%>

app/views/layouts/_slider.html.erb
  <aside class="main-sidebar">
  	<!-- sidebar: style can be found in sidebar.less -->
  	<section class="sidebar">
  		<!-- Sidebar user panel -->
  		<div class="user-panel">
  			<div class="image">
          <%= image_tag current_user.customer_logo, alt: "User Image"%>
          <div class="info">
            <p><%= current_user.customer_name %></p>
          </div>
  			</div>
  		</div>
  		<!-- sidebar menu: : style can be found in sidebar.less -->
  		<ul class="sidebar-menu">
  			<li class="header">MAIN NAVIGATION</li>
  			<% if can? :read, Customer %>
	  			<li class="<%= active_controller('customers') %>">
	  				<%= link_to customers_path do %>
	  					<i class="fa fa-user-secret"></i> <span>Customers</span> <i class="pull-right"></i>
	  				<%end%>
	  			</li>
  			<%end%>
  			<% if can? :read, User %>
	  			<li class="<%= active_controller('users') %>">
	  				<%= link_to users_path do %>
	  					<i class="fa fa-user"></i> <span>Users</span> <i class="pull-right"></i>
	  				<%end%>
	  			</li>
  			<%end%>
  			<% if can? :read, Group %>
	  			<li class="<%= active_controller('groups') %>">
	  				<%= link_to groups_path do %>
	  					<i class="fa fa-dashcube"></i> <span>Groups</span> <i class="pull-right"></i>
	  				<%end%>
	  			</li>
  			<%end%>
        <li class="<%= active_controller('posts') %>">
          <%= link_to posts_path do %>
            <i class="fa fa-newspaper-o"></i> <span>Posts</span> <i class="pull-right"></i>
          <%end%>
        </li>
        <li class="<%= active_controller('documents') %>">
          <%= link_to documents_path do %>
            <i class="fa fa-file-text-o"></i> <span>Documents</span> <i class="pull-right"></i>
          <%end%>
        </li>
  			<% if can? :read, DownloadLog %>
	  			<li class="<%= active_controller('file_data') %>">
	  				<%= link_to file_data_download_history_path do %>
	  					<i class="fa fa-cloud-download"></i> <span>Download History</span> <i class="pull-right"></i>
	  				<%end%>
	  			</li>
  			<%end%>
  		</ul>
  	</section>
  	<!-- /.sidebar -->
  </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentForum</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= user_signed_in? ? 'skin-blue sidebar-mini' : 'login-page'%>">
<%= render 'layouts/flash_message'%>
<%= user_signed_in? ? (render 'layouts/index') : (yield) %>
</body>
</html>